name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  github-hosted:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install build-essential flex bison git nvidia-cuda-toolkit

    - name: Build the project
      run: make

    - name: Run tests without CUDA
      run: make run-tests TEST_FLAGS=

  TUF-hosted:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Run tests with CUDA
      run: make run-tests
